### ISSUE TITLE
add sdctl procedure in troubleshooting guide

### ISSUE THREAD

**Issue by henderiw** [sdcio/config-server#114]
we install by default for now, optimization can come in the future

**Comment by hansthienpondt** [comment]
> * Make sure schema-server ; data-server and cache are binding their socket on 0.0.0.0 (or ::) and a non-overlapping port
>   (https://github.com/sdcio/config-server/blob/main/artifacts/configmap-data-server.yaml)

This is done by default. 
time="2024-02-21T15:18:48Z" level=info msg="starting server on :56000"

❯ kubectl exec sdctl -- /app/sdctl -a data-server.network-system.svc.cluster.local:56000 --format json datastore get --ds default.sr1 | jq .target
{
  "type": "netconf",
  "address": "172.22.1.11:830",
  "status": 1
}

**Comment by henderiw** [comment]
so it means we just need to add a deployment for the sdctl pod ?

**Comment by henderiw** [comment]
I prefer a deployment since this allows to upgrade. Can you do a proposal and we can add it to the artefacts

**Comment by hansthienpondt** [comment]
Cfr, internal discussion, after some testing I would go for:

`kubectl run -ti --rm sdctl --image=ghcr.io/sdcio/sdctl:v0.0.1 --restart=Never --command -- /bin/sh`

Will check with @steiler how to get this documented!

**Comment by hansthienpondt** [comment]
Done
