### ISSUE TITLE
improve schema libraries

### ISSUE THREAD

**Issue by henderiw** [sdcio/config-server#230]
Not all vendors upload all the schema's in 1 GitHub.
Both SONIC and Arista don't upload the IETF, etc dependencies.

here is a workaround. The goal of this issue is to improve the strategy here.

apiVersion: inv.sdcio.dev/v1alpha1
kind: Schema
metadata:
  name: eos.arista.4.31.2.f-standard
  namespace: default
spec:
  repoURL: https://github.com/YangModels/yang
  provider: eos.arista.sdcio.dev
  version: 4.31.2.F
  kind: branch
  ref: main
  dirs:
    - src: standard/ietf/RFC
      dst: ietf
    - src: standard/iana
      dst: iana
  schema:
    models:
      - iana/iana-if-type@2023-01-26.yang
      - ietf/ietf-inet-types.yang
      - ietf/ietf-interfaces.yang
      - ietf/ietf-yang-types.yang
    includes: []
    excludes: []

and then:
apiVersion: inv.sdcio.dev/v1alpha1
kind: Schema
metadata:
  name: eos.arista.4.31.2.f
  namespace: default
spec:
  repoURL: https://github.com/aristanetworks/yang
  provider: eos.arista.sdcio.dev
  version: 4.31.2.F
  kind: branch
  ref: master
  dirs:
    - src: EOS-4.31.2F
      dst: .
  schema:
    models:
      - release/openconfig/models
    includes:
      - openconfig/public/release/models
      - iana/iana-if-type@2023-01-26.yang
      - ietf/ietf-inet-types.yang
      - ietf/ietf-interfaces.yang
      - ietf/ietf-yang-types.yang
    excludes:
      - .*notsupported.*

**Comment by henderiw** [comment]
@hansthienpondt could you maybe have a look at this ?

**Comment by henderiw** [comment]
- have a list of repos:
   - per repo have a proxy capability, ref, kind
   - add a way to ensure we cannot overwrite the cloned info (e.g. by adding the url prefix or other)
   - potentially a global proxy that applies to all repos if specified. (avoids having to add the same proxy if all repos use the same (nice to have)

**Comment by henderiw** [comment]
@alexandernorth might be worth for you to have your views on this.

**Comment by henderiw** [comment]
my suggestion was to change the way we clone to include the GitHub/repo name to make it unique. We do this in porch/pkg server and this provides a unique reference at all times even when you get overlap. So from there we need to find a structure to please goyang.

**Comment by alexandernorth** [comment]
I think this can be closed now thanks to PR#251

**Comment by henderiw** [comment]
https://github.com/sdcio/config-server/pull/251
